# Generated by Django 2.2.9 on 2020-04-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_approvals', '0002_auto_20200414_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningapp',
            name='current_status',
            field=models.CharField(default='Extant', help_text='(Auto) Defines current status of planning permission', max_length=30),
        ),
    ]
