# Generated by Django 2.2.9 on 2020-05-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_approvals', '0004_plot_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningapp',
            name='app_ref',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='site_capacity',
            field=models.IntegerField(blank=True, default=0, help_text='Total no. of dwellings permitted', null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='units_lost',
            field=models.IntegerField(blank=True, default=0, help_text='No. of dwellings lost through development of site', null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='year_01',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='year_02',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='year_03',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='year_04',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='year_05',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='year_06',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='year_07',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='year_08',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='year_09',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='year_10',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='year_11',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='year_12',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='year_13',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='year_14',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='year_15',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='year_16',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='year_17',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='year_18',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='year_19',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='year_20',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
