# Generated by Django 2.2.9 on 2020-05-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_approvals', '0005_auto_20200502_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='author',
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='current_status',
            field=models.CharField(blank=True, default='Extant', help_text='(Auto) Defines current status of planning permission', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='site_area',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
