# Generated by Django 2.2.9 on 2020-05-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning_approvals', '0006_auto_20200503_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planningapp',
            old_name='year_01',
            new_name='year_one',
        ),
    ]
