# Generated by Django 2.2.9 on 2020-05-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning_approvals', '0007_auto_20200503_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planningapp',
            old_name='year_02',
            new_name='year_five',
        ),
        migrations.RenameField(
            model_name='planningapp',
            old_name='year_03',
            new_name='year_four',
        ),
        migrations.RenameField(
            model_name='planningapp',
            old_name='year_04',
            new_name='year_three',
        ),
        migrations.RenameField(
            model_name='planningapp',
            old_name='year_05',
            new_name='year_two',
        ),
    ]
