# Generated by Django 2.2.9 on 2020-05-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_approvals', '0009_auto_20200503_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningapp',
            name='proposal',
            field=models.TextField(verbose_name='Description of proposal'),
        ),
    ]
