# Generated by Django 2.2.9 on 2020-05-06 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning_approvals', '0011_auto_20200505_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningapp',
            name='address',
            field=models.TextField(help_text='Street address for application site'),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='app_ref',
            field=models.CharField(help_text='Unique reference code for Planning Application or site allocation', max_length=20, verbose_name='Application reference'),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='app_type',
            field=models.CharField(blank=True, choices=[('a', 'Allocation'), ('f', 'Full Planning'), ('o', 'Outline'), ('pn', 'Prior Notification'), ('pip', 'Permission in Priciple'), ('rm', 'Reserved Matters')], help_text='Type of approval or permission', max_length=5, null=True, verbose_name='Approval type'),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='appeal_decision_date',
            field=models.DateField(blank=True, help_text='Date appeal decision issued', null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='committee_decision_date',
            field=models.DateField(blank=True, help_text='Date of planning committee decision', null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='decision_date',
            field=models.DateField(blank=True, help_text='Date permission granted', null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='dev_type',
            field=models.CharField(blank=True, choices=[('new', 'New Building(s)'), ('cou', 'Change of Use'), ('rebld', 'Rebuild Applications'), ('conv', 'Conversion of a dwellings'), ('dem', 'Demolition of floorspace')], help_text='Type of development e.g. new build, change of use, etc.', max_length=5, null=True, verbose_name='Development type'),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='lapse_date',
            field=models.DateField(blank=True, help_text='Date permission lapses', null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='parish',
            field=models.ForeignKey(blank=True, help_text='Civil parish in which approval is located', null=True, on_delete=django.db.models.deletion.CASCADE, to='planning_approvals.Parish'),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='policy',
            field=models.CharField(blank=True, help_text='Local Plan policy reference', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='site',
            field=models.ForeignKey(help_text='Site to which approval relates', on_delete=django.db.models.deletion.CASCADE, to='planning_approvals.Site'),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='superseded_by_app',
            field=models.CharField(blank=True, help_text='Reference no. of application which supersedes this record', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='planningapp',
            name='superseded_date',
            field=models.DateField(blank=True, help_text='Date this record was superseded (e.g. date new app granted permission)', null=True),
        ),
    ]
