# Generated by Django 2.2.9 on 2020-05-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_approvals', '0012_auto_20200506_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningapp',
            name='app_ref',
            field=models.CharField(help_text='Unique reference code for planning application or site allocation', max_length=20, verbose_name='Application reference'),
        ),
    ]
