# Generated by Django 2.2.9 on 2020-05-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_approvals', '0013_auto_20200506_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningapp',
            name='pdl',
            field=models.CharField(blank=True, choices=[('g', 'Greenfield'), ('b', 'Brownfield'), ('m', 'Mix of Greenfield and Brownfield')], help_text='Previously developed land i.e. Greenfield / Brownfield land', max_length=1, null=True, verbose_name='PDL'),
        ),
    ]
