# Generated by Django 2.2.9 on 2020-05-10 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning_approvals', '0015_note_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningapp',
            name='superseded_by_app',
            field=models.ForeignKey(blank=True, help_text='Reference no. of application which supersedes this record', null=True, on_delete=django.db.models.deletion.CASCADE, to='planning_approvals.PlanningApp'),
        ),
    ]
